Trash activity
codergrad/bloknot pull request #9
Opened 2021-04-07 10:21 UTC by DrillDozer

сделал окончательный вариант кнопок

2021-04-24 15:20 UTC, radaken requested changes

2021-04-24 15:20 UTC, radaken commented on app/src/main/res/layout/activity_main.xml
> +    "center" />
За что отвечает эта строчка?

2021-04-24 15:31 UTC, radaken approved these changes

2021-04-27 06:55 UTC, RyoukuZen approved these changes

2021-04-27 07:01 UTC, merged